# Generated by Django 2.2.5 on 2019-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='login',
            new_name='telefono',
        ),
        migrations.AddField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
