# Generated by Django 2.2.5 on 2019-10-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20191002_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='edad',
            field=models.IntegerField(default=18),
        ),
    ]
