# Generated by Django 2.2.5 on 2019-10-03 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20191002_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarioServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=1),
        ),
    ]
