# Generated by Django 2.2.5 on 2019-10-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20191002_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_CalendarioServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField(default=0)),
                ('idServicio', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='CalendarioServicio',
            new_name='Tb_CatalogoServicio',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Tb_Usuario',
        ),
    ]
